apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-job
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: fixienotification:latest
            command: ["python", "manage.py", "clear_old_notifications"]
          restartPolicy: OnFailure
