apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fixieNotification-deployment.yaml
  - fixieNotification-worker-deployment.yaml
  - fixieNotification-rmOld-cronJob.yaml
  - fixieNotification-service.yaml
