apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: fixie

resources:
  - ../../base/fixieAuth/fixieAuth-deployment.yaml

secretGenerator:
  - name: fixieauth-secrets
    envs:
      - .env.fixieauth.local
  - name: fixieauth-keys
    files:
      - private.pem=../../secrets/private.pem
      - public.pem=../../secrets/public.pem
  - name: fixietasks-secrets
    envs:
      - .env.fixietasks.local
  - name: fixietasks-keys
    files:
      - public.pem=../../secrets/public.pem
  - name: fixieavatar-secrets
    envs:
      - .env.fixieavatar.local
  - name: fixieavatar-keys
    files:
      - public.pem=../../secrets/public.pem
  - name: fixienotification-secrets
    envs:
      - .env.fixienotification.local
  - name: fixienotification-keys
    files:
      - public.pem=../../secrets/public.pem

configMapGenerator:
  - name: fixieauth-config
    literals:
      - AUTH_ENV=local
      - AUTH_ISSUER=http://api.127-0-0-1.nip.io/auth
      - ALLOWED_HOSTS=fixieauth,fixieauth.default.svc,fixieauth.default.svc.cluster.local,localhost,127.0.0.1,10.0.2.2

  - name: fixietasks-config
    literals:
      - AUTH_ENV=local
      - AUTH_ISSUER=http://api.127-0-0-1.nip.io/auth
      - ALLOWED_HOSTS=fixietasks,fixietasks.default.svc,fixietasks.default.svc.cluster.local,localhost,127.0.0.1,10.0.2.2
      - KAFKA_BOOTSTRAP_SERVERS=messagefixie.servicebus.windows.net:9093
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISM=PLAIN

  - name: fixieavatar-config
    literals:
      - ALLOWED_HOSTS=fixieavatar,fixieavatar.default.svc,fixieavatar.default.svc.cluster.local,localhost,127.0.0.1,10.0.2.2
      - KAFKA_BOOTSTRAP_SERVERS=messagefixie.servicebus.windows.net:9093
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISM=PLAIN

  - name: fixienotification-config
    literals:
      - ALLOWED_HOSTS=fixienotification,fixienotification.default.svc,fixienotification.default.svc.cluster.local,localhost,
      - KAFKA_BOOTSTRAP_SERVERS=messagefixie.servicebus.windows.net:9093
      - KAFKA_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_SASL_MECHANISM=PLAIN
      - REDIS_HOST=fixie-websocket-redis-db.redis.cache.windows.net
      - REDIS_PORT=6380


generatorOptions:
  disableNameSuffixHash: true
