apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixieavatar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fixieavatar
  template:
    metadata:
      labels:
        app: fixieavatar
    spec:
      containers:
      - name: fixieavatar
        image: fixieacr.azurecr.io/fixieavatar:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        envFrom:
          - secretRef:
              name: fixieavatar-secrets
          - configMapRef:
              name: fixieavatar-config
        env:
          - name: PUBLIC_KEY_PATH
            value: /etc/secrets/jwt/public.pem
        volumeMounts:
          - name: jwt-public
            mountPath: /etc/secrets/jwt
            readOnly: true
      volumes:
        - name: jwt-public
          secret:
            secretName: fixieavatar-keys
            items:
              - key: public.pem 
                path: public.pem